//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid_Property_User
    {
        public string Id { get; set; }
        public string PropertyId { get; set; }
        public string Title { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public string PostedBy { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public string Remarks { get; set; }
        public string Message { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    }
}
