//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Item
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
        public string SKU { get; set; }
        public string Thumbnail { get; set; }
        public string ShortDescription { get; set; }
        public string Highlight { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> HidePrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> ManufacturerPrice { get; set; }
        public Nullable<bool> Visibility { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<bool> HideToAnonymous { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public Nullable<decimal> SpecialPrice { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsModified { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string AddedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<decimal> RatedValue { get; set; }
        public Nullable<bool> IsNotifiacationViewed { get; set; }
        public int TotalDiscount { get; set; }
    }
}
