//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Detail
    {
        public string PropertyId { get; set; }
        public string Title { get; set; }
        public string TypeId { get; set; }
        public string LocationId { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public string img5 { get; set; }
        public string img6 { get; set; }
        public string LalPurja_ScanCopy { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> AllowAuction { get; set; }
        public Nullable<bool> IsApplyLocked { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Breath { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Description { get; set; }
        public Nullable<int> NO_Of_Floor { get; set; }
        public Nullable<int> NO_Of_Room { get; set; }
        public Nullable<int> NO_Of_BedRoom { get; set; }
        public Nullable<int> NO_Of_Kitchen { get; set; }
        public Nullable<int> NO_Of_BathRoom { get; set; }
        public string HouseColor { get; set; }
        public Nullable<int> NO_Of_Hall { get; set; }
        public Nullable<int> NO_Of_GuestRoom { get; set; }
        public Nullable<int> NO_Of_Car_For_Parking { get; set; }
        public Nullable<int> NO_Of_Bike_For_Parking { get; set; }
        public Nullable<bool> Compound { get; set; }
        public Nullable<bool> Under_Ground_Water_Tank { get; set; }
        public string FloorType { get; set; }
        public string HouseType { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Zone { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string HouseNo { get; set; }
    }
}
